language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pytest flake8
  - pip install -e .
script:
  # Regular flake8 checks
  - flake8
  # Cython flake8 checks
  - flake8 --config .flake8.cython
  - py.test tests/
cache: pip
